module.exports = {
   alpha: 3,
   B: 10,
   K: 5,

   GET_CLOSEST_NODE_FOUND_NOTHING: 1501,
   GET_CLOSEST_NODE_FOUND_A_BUCKET: 1502,
   GET_CLOSEST_NODE_FOUND_THE_NODE: 1503,

   ////////Error codes
   ERROR_SELECT_BUCKET_DISTANCE_IS_ZERO: "E2503",

   BUCKET_NEIGHBOUR_SEARCH_RANGE: 50
}